version: '2'
services:
  talk:
    container_name: talk
    image: jtschoonhoven/coralproject/talk
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
      - ./private/.env
    environment:
      TALK_PORT: $PORT
      TALK_ROOT_URL: $TALK_ROOT_URL
      TALK_JWT_ALG: RS256
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
